name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -target ReactiveDataDisplayManager
    - name: Run tests
      run: xcodebuild test -scheme ReactiveDataDisplayManager -configuration "Debug" -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash) -J 'ReactiveDataDisplayManager'
