name: Build

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild ReactiveDataDisplayManager.xcproject
    - name: Run tests
      run: xcodebuild test -scheme ReactiveDataDisplayManager -configuration "Debug" -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.2' | xcpretty -c
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash) -J 'ReactiveDataDisplayManager'
    

